"""empty message

Revision ID: 883954b525eb
Revises: 99f3c00493fb
Create Date: 2020-07-03 16:51:11.370662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883954b525eb'
down_revision = '99f3c00493fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('ix_post_timeStamp', table_name='post')
    op.drop_column('post', 'timeStamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timeStamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_post_timeStamp', 'post', ['timeStamp'], unique=False)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
